const express = require("express");
const pool = require("../db/pool");
const PDFDocument = require("pdfkit");
const { Resend } = require("resend");

const router = express.Router();
const resend = new Resend(process.env.RESEND_API_KEY);

// Helper function to create a PDF in memory and return it as a Buffer
function generatePDFBuffer(restaurantName, salesData, cancelData) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => {
        resolve(Buffer.concat(buffers));
      });

      // Header
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text(`${restaurantName}`, { align: "center" })
        .moveDown(0.5);

      const dateStr = new Date().toLocaleDateString("en-IN", {
        timeZone: "Asia/Kolkata",
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      });

      doc
        .fontSize(14)
        .font("Helvetica")
        .text(`End of Day (Z-Report) - ${dateStr}`, { align: "center" })
        .moveDown(2);

      // Section: Sales Summary
      doc.fontSize(16).font("Helvetica-Bold").text("Sales Summary").moveDown(0.5);
      doc.fontSize(12).font("Helvetica");

      doc.text(`Total Completed Orders: ${salesData.total_orders}`);
      doc.text(`Gross Revenue: Rs. ${Number(salesData.gross_revenue).toFixed(2)}`);
      doc.text(`Total Discounts: Rs. ${Number(salesData.total_discount).toFixed(2)}`);
      doc.text(`Total Taxes Collected (CGST+SGST): Rs. ${Number(salesData.total_tax).toFixed(2)}`);
      doc.moveDown(1);

      // Section: Payment Splits
      doc.fontSize(16).font("Helvetica-Bold").text("Payment Breakdown").moveDown(0.5);
      doc.fontSize(12).font("Helvetica");

      doc.text(`Cash Sales: Rs. ${Number(salesData.cash_sales).toFixed(2)}`);
      doc.text(`Online Sales: Rs. ${Number(salesData.online_sales).toFixed(2)}`);
      doc.moveDown(1);

      // Section: Cancellations
      doc.fontSize(16).font("Helvetica-Bold").text("Cancellations").moveDown(0.5);
      doc.fontSize(12).font("Helvetica");

      doc.text(`Cancelled Orders: ${cancelData.cancelled_orders}`);
      doc.text(`Lost Value: Rs. ${Number(cancelData.cancelled_value).toFixed(2)}`);
      doc.moveDown(2);

      // Footer
      doc
        .fontSize(10)
        .fillColor("gray")
        .text("Automatically generated by The Chinese House System.", { align: "center", baseline: "bottom" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

// POST /api/reports/eod-report
router.post("/eod-report", async (req, res) => {
  try {
    // 1. Authentication Check
    const authHeader = req.headers["authorization"];
    const expectedSecret = process.env.CRON_SECRET_KEY;

    if (!expectedSecret || authHeader !== expectedSecret) {
      return res.status(401).json({ error: "Unauthorized. Invalid CRON_SECRET_KEY." });
    }

    if (!process.env.RESEND_API_KEY) {
      return res.status(500).json({ error: "RESEND_API_KEY is not configured." });
    }

    // 2. Fetch Active Businesses and Admin Emails
    const businessQuery = `
      SELECT b.id as business_id, bs.restaurant_name, a.email
      FROM businesses b
      JOIN business_settings bs ON bs.business_id = b.id
      JOIN admin_account a ON a.business_id = b.id
      WHERE b.is_active = true AND a.email IS NOT NULL AND a.email != ''
    `;
    const businessRes = await pool.query(businessQuery);
    const businesses = businessRes.rows;

    if (businesses.length === 0) {
      return res.status(200).json({ message: "No active businesses with configured admin emails found." });
    }

    // 3. Process each business
    const results = [];
    for (const b of businesses) {
      // Query Sales
      const salesQuery = `
        SELECT
          COUNT(*) as total_orders,
          COALESCE(SUM(total), 0) as gross_revenue,
          COALESCE(SUM(discount), 0) as total_discount,
          COALESCE(SUM(cgst + sgst), 0) as total_tax,
          COALESCE(SUM(CASE WHEN payment_method = 'online' THEN total ELSE 0 END), 0) as online_sales,
          COALESCE(SUM(CASE WHEN payment_method = 'cash' THEN total ELSE 0 END), 0) as cash_sales
        FROM orders
        WHERE business_id = $1 
          AND status = 'completed'
          AND (created_at AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Kolkata')::date = (NOW() AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Kolkata')::date
      `;
      const salesRes = await pool.query(salesQuery, [b.business_id]);
      const salesData = salesRes.rows[0];

      // Query Cancellations
      const cancelQuery = `
        SELECT 
          COUNT(*) as cancelled_orders, 
          COALESCE(SUM(total), 0) as cancelled_value
        FROM orders
        WHERE business_id = $1 
          AND status = 'cancelled'
          AND (created_at AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Kolkata')::date = (NOW() AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Kolkata')::date
      `;
      const cancelRes = await pool.query(cancelQuery, [b.business_id]);
      const cancelData = cancelRes.rows[0];

      // Generate PDF
      const pdfBuffer = await generatePDFBuffer(b.restaurant_name, salesData, cancelData);
      
      const dateStr = new Date().toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata" });
      const filename = `Z-Report-${b.restaurant_name.replace(/[^a-z0-9]/gi, '_')}-${dateStr.replace(/\\//g, '-')}.pdf`;

      // Send Email
      try {
        await resend.emails.send({
          from: "The Chinese House System <onboarding@resend.dev>", // Replace with verified domain if available
          to: b.email,
          subject: `Daily Z-Report: ${b.restaurant_name} (${dateStr})`,
          text: `Please find attached the automated End-of-Day Z-Report for ${dateStr}.`,
          attachments: [
            {
              filename: filename,
              content: pdfBuffer,
            },
          ],
        });
        results.push({ business: b.restaurant_name, email: b.email, status: "sent" });
      } catch (emailErr) {
        console.error(`Failed to send email to ${b.email} for ${b.restaurant_name}:`, emailErr);
        results.push({ business: b.restaurant_name, email: b.email, status: "failed", error: emailErr.message });
      }
    }

    res.status(200).json({ message: "EOD reports processed", results });
  } catch (error) {
    console.error("Error in EOD cron job:", error);
    res.status(500).json({ error: "Internal server error." });
  }
});

module.exports = router;
