name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Build Web Assets
        working-directory: ./frontend
        run: npm run build

      - name: Sync Capacitor
        working-directory: ./frontend
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build Release APK
        working-directory: ./frontend/android
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: frontend/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} frontend/android/app/build/outputs/apk/release/TCH-Release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: The-Chinese-House-POS-App
          path: frontend/android/app/build/outputs/apk/release/TCH-Release.apk
