name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore tch-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias tch_alias -dname "CN=The Chinese House, OU=Development, O=The Chinese House, L=City, S=State, C=IN" -storepass tch_secure_pass_123 -keypass tch_secure_pass_123
          
      - name: Convert to Base64
        run: |
          echo "=========================================================="
          echo "COPY EVERYTHING BETWEEN THE HASH LINES (STARTING WITH THE FIRST CHARACTER AFTER THIS LINE):"
          echo "##########################################################"
          base64 tch-release-key.jks
          echo "##########################################################"
          echo "Make sure there are no spaces at the beginning or end when pasting!"
